/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        black: '#000000',
        'dragon-black': '#0a0a0a',
        'dragon-gray': '#1a1a1a',
        'dragon-light': '#2a2a2a',
        /* Chinese restaurant theme */
        'cn-red': '#dc2626',
        'cn-red-dark': '#991b1b',
        'cn-red-light': '#ef4444',
        'cn-gold': '#d97706',
        'cn-gold-light': '#fbbf24',
        'cn-gold-pale': '#fef3c7',
        'cn-dark': '#0d0505',
        'cn-surface': '#1a0e0e',
        'cn-card': '#1f1111',
        'cn-border': '#3d1515',
        orange: {
          50: '#fff7ed', 100: '#ffedd5', 200: '#fed7aa',
          300: '#fdba74', 400: '#fb923c', 500: '#f97316',
          600: '#ea580c', 700: '#c2410c', 800: '#9a3412',
          900: '#7c2d12', 950: '#431407',
        },
        neon: { orange: '#ff6b35', red: '#ff0040' },
      },
      fontFamily: {
        'display': ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        'body': ['Inter', 'Noto Sans SC', 'system-ui', 'sans-serif'],
        'chinese': ['Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'fade-in': 'fadeIn 0.3s ease-out',
        'bounce-in': 'bounceIn 0.4s cubic-bezier(0.68,-0.55,0.265,1.55)',
        'cart-shake': 'cartShake 0.4s ease-out',
        'pulse-red': 'pulseRed 2s ease-in-out infinite',
      },
      keyframes: {
        float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-20px)' } },
        glow: { '0%': { boxShadow: '0 0 20px rgba(220,38,38,0.5)' }, '100%': { boxShadow: '0 0 40px rgba(220,38,38,0.9)' } },
        slideUp: { '0%': { transform: 'translateY(100%)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        slideDown: { '0%': { transform: 'translateY(-100%)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        bounceIn: { '0%': { transform: 'scale(0.3)', opacity: '0' }, '60%': { transform: 'scale(1.1)' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        cartShake: { '0%, 100%': { transform: 'rotate(0deg)' }, '25%': { transform: 'rotate(-10deg)' }, '75%': { transform: 'rotate(10deg)' } },
        pulseRed: { '0%, 100%': { boxShadow: '0 0 0 0 rgba(220,38,38,0.4)' }, '50%': { boxShadow: '0 0 0 8px rgba(220,38,38,0)' } },
      },
      backdropBlur: { xs: '2px' },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'cn-gradient': 'linear-gradient(135deg, #dc2626 0%, #991b1b 100%)',
        'gold-gradient': 'linear-gradient(135deg, #d97706 0%, #fbbf24 100%)',
      },
    },
  },
  plugins: [],
}
